---
- name: Template a file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/.bazelrc"
    dest: "{{ ansible_env.HOME }}/.bazelrc"
    owner: "{{ ansible_env.USER }}"
    mode: "0644"

- name: Copy read-only files
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    mode: "0644"
  loop:
    - debug.logging.properties

- name: Tap a Homebrew repository, state present
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop: "{{ work_tap_list }}"

- name: Install dependencies
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ work_list }}"

- name: Configure for work use
  ansible.builtin.copy:
    src: "{{ role_path }}/configurations/{{ item.config }}"
    dest: "{{ ansible_env.HOME }}/.config/"
    owner: "{{ ansible_env.USER }}"
    mode: "0755"
    follow: true
  when: item.name in dependencies_list
  loop:
    - { name: "neovim", config: "nvim" }

- name: Clean up Bazel cache
  ansible.builtin.blockinfile:
    path: "{{ maintenance_script_path }}"
    marker: "# {mark} Remove Bazel cache"
    block: |
      rm -rf "/private/var/tmp/_bazel_$USER"
  become: true
  notify:
    - Kickstart maintenance LaunchDaemon
