---
work_tap_list:
  - hashicorp/tap
  - cirruslabs/cli
  - xcodesorg/made

work_list:
  - apparency
  - aria2
  - awscli
  - cirruslabs/cli/tart
  - claude-code
  - cursor
  - hashicorp/tap/packer
  - hashicorp/tap/terraform
  - hyperfine
  - mist-cli
  - shellcheck
  - suspicious-package
  - xcodesorg/made/xcodes
  - yq
